Repository mayspc/payrex-rust, pull requests merged in 2025-10, with the labels that each got.

#1 feat(ci): gh actions
  .config/nextest.toml
  .github/workflows/ci.yml
  .github/workflows/dependencies.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .prettierignore
  .prettierrc
  .yamllint.yml
  Cargo.toml
  README.md
  _typos.toml
  rustfmt.toml
Labels: size/XL

#4 chore: obliterate lint workflow
  .github/workflows/lint.yml
Labels: size/M

#3 Update details in `Cargo.toml`
  Cargo.toml
  LICENSE
  rustfmt.toml
Labels: size/M

#5 style: fix formatting using `rustfmt`
  rustfmt.toml
  src/client.rs
  src/config.rs
  src/http.rs
  src/resources/billing_statements.rs
  src/resources/checkout_sessions.rs
  src/resources/customers.rs
  src/resources/events.rs
  src/resources/payment_intents.rs
  src/resources/payments.rs
  src/resources/payouts.rs
  src/resources/refunds.rs
  src/resources/webhooks.rs
Labels: size/M

#7 fix: use basic authentication instead of bearer
  src/http.rs
Labels: size/XS

#9 feat!: rename `PaymentMethod::QRPH` to `QRPh`
  src/resources/payment_intents.rs
Labels: size/XS

#8 docs: add documentation for billing statements
  src/resources/billing_statements.rs
Labels: size/L
